create table BANKS
(
    ID   NUMBER generated by default on null as identity
        primary key,
    NAME VARCHAR2(100) not null
);
insert into BANK_REVIEWS.BANKS (ID, NAME)
values  (1, 'CBE'),
        (2, 'BOA'),
        (3, 'DASHEN');